CREATE TABLE prestation
(
id INT PRIMARY KEY IDENTITY (1,1),
titre VARCHAR(MAX)NULL,
duree VARCHAR(MAX)NULL,
tarif VARCHAR(MAX)NULL,
descritif VARCHAR(MAX)NULL
)

SELECT * FROM prestation

ALTER TABLE prestation
ADD status VARCHAR(MAX) NULL